### ISSUE TITLE
Unable to run build as per instructions

### ISSUE THREAD

**Issue by gjanders** [splunk/spling_bee_moderator#4]
I was hoping to be able to download a pre-built Splunk app but the README has build instructions.

I managed to get nodejs installed on an Oracle 8 machine, unfortunately that was nodejs 10, that resulted in:
error axe-core@4.4.2: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.24.0"
error Found incompatible module.

So I moved to nodejs 12 via:
curl -sL https://rpm.nodesource.com/setup_12.x | bash -

That appears to have worked, but my new issue is:
```
$ yarn run setup
yarn run v1.22.19
$ yarn && lerna run build
info There appears to be trouble with your network connection. Retrying...
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > @splunk/timer-vis@0.0.1" has unmet peer dependency "react@^16.8".
warning " > @splunk/timer-vis@0.0.1" has unmet peer dependency "styled-components@^5.1".
warning "workspace-aggregator-555e6be8-a7e2-4841-9578-2fbedb5debcb > @splunk/spling_bee_moderator > @splunk/react-page@5.2.1" has incorrect peer dependency "styled-components@5.1.1".
warning "workspace-aggregator-555e6be8-a7e2-4841-9578-2fbedb5debcb > @splunk/spling_bee_moderator > @splunk/react-ui@4.7.0" has incorrect peer dependency "styled-components@5.1.1".
warning "workspace-aggregator-555e6be8-a7e2-4841-9578-2fbedb5debcb > @splunk/spling_bee_moderator > styled-components@5.3.5" has unmet peer dependency "react-is@>= 16.8.0".
warning "workspace-aggregator-555e6be8-a7e2-4841-9578-2fbedb5debcb > @splunk/timer-vis > @splunk/dashboard-core@24.4.0" has incorrect peer dependency "styled-components@5.1.1".
warning "workspace-aggregator-555e6be8-a7e2-4841-9578-2fbedb5debcb > @splunk/timer-vis > @splunk/react-icons@3.2.0" has incorrect peer dependency "styled-components@5.1.1".
warning "workspace-aggregator-555e6be8-a7e2-4841-9578-2fbedb5debcb > @splunk/timer-vis > @splunk/visualization-context@24.4.0" has incorrect peer dependency "styled-components@5.1.1".
warning "workspace-aggregator-555e6be8-a7e2-4841-9578-2fbedb5debcb > @splunk/spling_bee_moderator > @splunk/react-ui > use-typed-event-listener@3.0.0" has unmet peer dependency "typescript@>=3.5.1".
warning "workspace-aggregator-555e6be8-a7e2-4841-9578-2fbedb5debcb > @splunk/timer-vis > @splunk/dashboard-core > @splunk/dashboard-layouts@24.4.0" has incorrect peer dependency "styled-components@5.1.1".
warning "workspace-aggregator-555e6be8-a7e2-4841-9578-2fbedb5debcb > @splunk/timer-vis > @splunk/dashboard-core > @splunk/dashboard-ui@24.4.0" has incorrect peer dependency "styled-components@5.1.1".
warning "workspace-aggregator-555e6be8-a7e2-4841-9578-2fbedb5debcb > @splunk/timer-vis > @splunk/dashboard-core > @splunk/visualization-icons@24.4.0" has incorrect peer dependency "styled-components@5.1.1".
warning "workspace-aggregator-555e6be8-a7e2-4841-9578-2fbedb5debcb > @splunk/timer-vis > @splunk/dashboard-presets > @splunk/dashboard-inputs@24.4.0" has incorrect peer dependency "styled-components@5.1.1".
warning "workspace-aggregator-555e6be8-a7e2-4841-9578-2fbedb5debcb > @splunk/timer-vis > @splunk/dashboard-presets > @splunk/dashboard-visualizations@24.4.0" has incorrect peer dependency "styled-components@5.1.1".
warning "workspace-aggregator-555e6be8-a7e2-4841-9578-2fbedb5debcb > @splunk/timer-vis > @splunk/dashboard-presets > @splunk/visualizations@24.4.0" has incorrect peer dependency "styled-components@5.1.1".
warning "workspace-aggregator-555e6be8-a7e2-4841-9578-2fbedb5debcb > @splunk/spling_bee_moderator > @splunk/react-ui > react-spring > @react-spring/konva@9.4.5" has unmet peer dependency "konva@>=2.6".
warning "workspace-aggregator-555e6be8-a7e2-4841-9578-2fbedb5debcb > @splunk/spling_bee_moderator > @splunk/react-ui > react-spring > @react-spring/konva@9.4.5" has unmet peer dependency "react-konva@^16.8.0  || ^17.0.0".
warning "workspace-aggregator-555e6be8-a7e2-4841-9578-2fbedb5debcb > @splunk/spling_bee_moderator > @splunk/react-ui > react-spring > @react-spring/native@9.4.5" has unmet peer dependency "react-native@>=0.58".
warning "workspace-aggregator-555e6be8-a7e2-4841-9578-2fbedb5debcb > @splunk/spling_bee_moderator > @splunk/react-ui > react-spring > @react-spring/three@9.4.5" has unmet peer dependency "@react-three/fiber@>=6.0".
warning "workspace-aggregator-555e6be8-a7e2-4841-9578-2fbedb5debcb > @splunk/spling_bee_moderator > @splunk/react-ui > react-spring > @react-spring/three@9.4.5" has unmet peer dependency "three@>=0.126".
warning "workspace-aggregator-555e6be8-a7e2-4841-9578-2fbedb5debcb > @splunk/spling_bee_moderator > @splunk/react-ui > react-spring > @react-spring/zdog@9.4.5" has unmet peer dependency "react-zdog@>=1.0".
warning "workspace-aggregator-555e6be8-a7e2-4841-9578-2fbedb5debcb > @splunk/spling_bee_moderator > @splunk/react-ui > react-spring > @react-spring/zdog@9.4.5" has unmet peer dependency "zdog@>=1.0".
warning "workspace-aggregator-555e6be8-a7e2-4841-9578-2fbedb5debcb > @splunk/timer-vis > @splunk/dashboard-core > @splunk/dashboard-layouts > @splunk/visualizations-shared@24.4.0" has incorrect peer dependency "styled-components@5.1.1".
warning "workspace-aggregator-555e6be8-a7e2-4841-9578-2fbedb5debcb > @splunk/timer-vis > @splunk/dashboard-core > @splunk/dashboard-ui > @testing-library/user-event@13.5.0" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning "workspace-aggregator-555e6be8-a7e2-4841-9578-2fbedb5debcb > @splunk/timer-vis > @splunk/dashboard-presets > @splunk/dashboard-visualizations > @splunk/react-sparkline@0.6.1" has incorrect peer dependency "styled-components@5.1.1".
warning "workspace-aggregator-555e6be8-a7e2-4841-9578-2fbedb5debcb > @splunk/timer-vis > @splunk/dashboard-presets > @splunk/dashboard-visualizations > @splunk/react-visualizations@24.4.0" has incorrect peer dependency "styled-components@5.1.1".
warning "workspace-aggregator-555e6be8-a7e2-4841-9578-2fbedb5debcb > @splunk/timer-vis > @splunk/dashboard-presets > @splunk/visualizations > maplibre-gl > @mapbox/mapbox-gl-supported@1.5.0" has unmet peer dependency "mapbox-gl@>=0.32.1 <2.0.0".
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
[5/5] Building fresh packages...
lerna info version 2.11.0
$ NODE_ENV=production webpack --bail
Hash: 607c91c47ee13956f2ad
Version: webpack 4.46.0
Time: 2376ms
Built at: 09/14/2022 3:02:47 PM
      Asset     Size  Chunks             Chunk Names
TimerVis.js  118 KiB       0  [emitted]  TimerVis
Entrypoint TimerVis = TimerVis.js
 [0] external "react" 42 bytes {0} [built]
 [1] external "@splunk/react-ui/Button" 42 bytes {0} [built]
 [3] external "@splunk/dashboard-presets/EnterprisePreset" 42 bytes {0} [built]
 [4] external "@splunk/visualizations/common/SplunkVisualization" 42 bytes {0} [built]
 [5] external "@splunk/dashboard-core" 42 bytes {0} [built]
 [6] external "@splunk/dashboard-context" 42 bytes {0} [built]
 [7] external "react-router-dom" 42 bytes {0} [built]
 [9] external "@splunk/react-ui/Message" 42 bytes {0} [built]
[10] external "@splunk/themes" 42 bytes {0} [built]
[11] ./src/customTimer.jsx + 1 modules 25 KiB {0} [built]
     | ./src/customTimer.jsx 1.81 KiB [built]
     | ./src/timer.jsx 23.1 KiB [built]
[12] ./src/TimerVis.jsx 35 KiB {0} [built]
[14] (webpack)/buildin/global.js 472 bytes {0} [built]
[15] external "base64-js" 42 bytes {0} [built]
[16] external "ieee754" 42 bytes {0} [built]
[17] external "isarray" 42 bytes {0} [built]
    + 3 hidden modules
[..................] - run: sill getExecOpts { cwd: '/home/d891093/spling_bee_moderator-main/packages/timer-vis' }
lerna ERR! build Errored while running script in '@splunk/spling_bee_moderator'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn run build
lerna ERR! FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
lerna ERR!  1: 0xa1ae50 node::Abort() [node]
lerna ERR!  2: 0xa1b25c node::OnFatalError(char const*, char const*) [node]
lerna ERR!  3: 0xb9b20e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
lerna ERR!  4: 0xb9b589 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
lerna ERR!  5: 0xd58815  [node]
lerna ERR!  6: 0xd58ea6 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
lerna ERR!  7: 0xd65765 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
lerna ERR!  8: 0xd66615 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
lerna ERR!  9: 0xd690cc v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
lerna ERR! 10: 0xd35731 v8::internal::Factory::NewTransitionArray(int, int) [node]
lerna ERR! 11: 0xf7ec77 v8::internal::TransitionsAccessor::Insert(v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Map>, v8::internal::SimpleTransitionFlag) [node]
lerna ERR! 12: 0xf2adda v8::internal::Map::ConnectTransition(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::SimpleTransitionFlag) [node]
lerna ERR! 13: 0xf2d13a v8::internal::Map::ShareDescriptor(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::DescriptorArray>, v8::internal::Descriptor*) [node]
lerna ERR! 14: 0xf2db2e v8::internal::Map::CopyAddDescriptor(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Map>, v8::internal::Descriptor*, v8::internal::TransitionFlag) [node]
lerna ERR! 15: 0xf2dca9 v8::internal::Map::CopyWithField(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::FieldType>, v8::internal::PropertyAttributes, v8::internal::PropertyConstness, v8::internal::Representation, v8::internal::TransitionFlag) [node]
lerna ERR! 16: 0xf2f492 v8::internal::Map::TransitionToDataProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::PropertyConstness, v8::internal::StoreOrigin) [node]
lerna ERR! 17: 0xf1fb2f v8::internal::LookupIterator::PrepareTransitionToDataProperty(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::StoreOrigin) [node]
lerna ERR! 18: 0xdeb55b v8::internal::StoreIC::LookupForWrite(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::StoreOrigin) [node]
lerna ERR! 19: 0xdeefe7 v8::internal::StoreIC::UpdateCaches(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::StoreOrigin) [node]
lerna ERR! 20: 0xdf195c  [node]
lerna ERR! 21: 0xdf1fba v8::internal::Runtime_StoreIC_Miss(int, unsigned long*, v8::internal::Isolate*) [node]
lerna ERR! 22: 0x140e819  [node]
lerna ERR! error Command failed with signal "SIGABRT".
lerna ERR! $ NODE_ENV=production webpack --bail
lerna ERR!
lerna ERR! <--- Last few GCs --->
lerna ERR!
lerna ERR! [176367:0x3a0eef0]    45398 ms: Mark-sweep 1965.3 (1987.3) -> 1967.3 (1987.8) MB, 2296.5 / 0.0 ms  (average mu = 0.086, current mu = 0.017) allocation failure scavenge might not succeed
lerna ERR! [176367:0x3a0eef0]    47822 ms: Mark-sweep 1967.3 (1987.8) -> 1965.9 (1997.8) MB, 2423.7 / 0.0 ms  (average mu = 0.042, current mu = 0.000) allocation failure scavenge might not succeed
lerna ERR!
lerna ERR!
lerna ERR! <--- JS stacktrace --->
lerna ERR!
lerna ERR! ==== JS stack trace =========================================
lerna ERR!
lerna ERR!     0: ExitFrame [pc: 0x140e819]
lerna ERR! Security context: 0x2e6b3bd408d1 <JSObject>
lerna ERR!     1: /* anonymous */(aka /* anonymous */) [0x15d55b2bffb1] [/home/d891093/spling_bee_moderator-main/node_modules/terser/dist/bundle.min.js:~1] [pc=0x2a2a8be63880](this=0x2e6b7b3c04b1 <undefined>)
lerna ERR!     2: /* anonymous */(aka /* anonymous */) [0x76f35436c91] [/home/d891093/spling_bee_moderator-main/node_modules/terser/dist/bundle.min.js:1] [bytecode=0x2e863a674c9 ...
lerna ERR!
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR!
lerna ERR!     at /home/d891093/spling_bee_moderator-main/node_modules/lerna/node_modules/execa/index.js:236:11
Error: Command failed: yarn run build
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa1ae50 node::Abort() [node]
 2: 0xa1b25c node::OnFatalError(char const*, char const*) [node]
 3: 0xb9b20e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb9b589 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd58815  [node]
 6: 0xd58ea6 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
 7: 0xd65765 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xd66615 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xd690cc v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xd35731 v8::internal::Factory::NewTransitionArray(int, int) [node]
11: 0xf7ec77 v8::internal::TransitionsAccessor::Insert(v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Map>, v8::internal::SimpleTransitionFlag) [node]
12: 0xf2adda v8::internal::Map::ConnectTransition(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::SimpleTransitionFlag) [node]
13: 0xf2d13a v8::internal::Map::ShareDescriptor(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::DescriptorArray>, v8::internal::Descriptor*) [node]
14: 0xf2db2e v8::internal::Map::CopyAddDescriptor(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Map>, v8::internal::Descriptor*, v8::internal::TransitionFlag) [node]
15: 0xf2dca9 v8::internal::Map::CopyWithField(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::FieldType>, v8::internal::PropertyAttributes, v8::internal::PropertyConstness, v8::internal::Representation, v8::internal::TransitionFlag) [node]
16: 0xf2f492 v8::internal::Map::TransitionToDataProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::PropertyConstness, v8::internal::StoreOrigin) [node]
17: 0xf1fb2f v8::internal::LookupIterator::PrepareTransitionToDataProperty(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::StoreOrigin) [node]
18: 0xdeb55b v8::internal::StoreIC::LookupForWrite(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::StoreOrigin) [node]
19: 0xdeefe7 v8::internal::StoreIC::UpdateCaches(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::StoreOrigin) [node]
20: 0xdf195c  [node]
21: 0xdf1fba v8::internal::Runtime_StoreIC_Miss(int, unsigned long*, v8::internal::Isolate*) [node]
22: 0x140e819  [node]
error Command failed with signal "SIGABRT".
$ NODE_ENV=production webpack --bail

<--- Last few GCs --->

[176367:0x3a0eef0]    45398 ms: Mark-sweep 1965.3 (1987.3) -> 1967.3 (1987.8) MB, 2296.5 / 0.0 ms  (average mu = 0.086, current mu = 0.017) allocation failure scavenge might not succeed
[176367:0x3a0eef0]    47822 ms: Mark-sweep 1967.3 (1987.8) -> 1965.9 (1997.8) MB, 2423.7 / 0.0 ms  (average mu = 0.042, current mu = 0.000) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x140e819]
Security context: 0x2e6b3bd408d1 <JSObject>
    1: /* anonymous */(aka /* anonymous */) [0x15d55b2bffb1] [/home/d891093/spling_bee_moderator-main/node_modules/terser/dist/bundle.min.js:~1] [pc=0x2a2a8be63880](this=0x2e6b7b3c04b1 <undefined>)
    2: /* anonymous */(aka /* anonymous */) [0x76f35436c91] [/home/d891093/spling_bee_moderator-main/node_modules/terser/dist/bundle.min.js:1] [bytecode=0x2e863a674c9 ...

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at /home/d891093/spling_bee_moderator-main/node_modules/lerna/node_modules/execa/index.js:236:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 1,
  killed: false,
  stdout: '$ NODE_ENV=production webpack --bail\n' +
    '\n' +
    '<--- Last few GCs --->\n' +
    '\n' +
    '[176367:0x3a0eef0]    45398 ms: Mark-sweep 1965.3 (1987.3) -> 1967.3 (1987.8) MB, 2296.5 / 0.0 ms  (average mu = 0.086, current mu = 0.017) allocation failure scavenge might not succeed\n' +
    '[176367:0x3a0eef0]    47822 ms: Mark-sweep 1967.3 (1987.8) -> 1965.9 (1997.8) MB, 2423.7 / 0.0 ms  (average mu = 0.042, current mu = 0.000) allocation failure scavenge might not succeed\n' +
    '\n' +
    '\n' +
    '<--- JS stacktrace --->\n' +
    '\n' +
    '==== JS stack trace =========================================\n' +
    '\n' +
    '    0: ExitFrame [pc: 0x140e819]\n' +
    'Security context: 0x2e6b3bd408d1 <JSObject>\n' +
    '    1: /* anonymous */(aka /* anonymous */) [0x15d55b2bffb1] [/home/d891093/spling_bee_moderator-main/node_modules/terser/dist/bundle.min.js:~1] [pc=0x2a2a8be63880](this=0x2e6b7b3c04b1 <undefined>)\n' +
    '    2: /* anonymous */(aka /* anonymous */) [0x76f35436c91] [/home/d891093/spling_bee_moderator-main/node_modules/terser/dist/bundle.min.js:1] [bytecode=0x2e863a674c9 ...\n' +
    '\n' +
    'info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n',
  stderr: 'FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory\n' +
    ' 1: 0xa1ae50 node::Abort() [node]\n' +
    ' 2: 0xa1b25c node::OnFatalError(char const*, char const*) [node]\n' +
    ' 3: 0xb9b20e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]\n' +
    ' 4: 0xb9b589 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]\n' +
    ' 5: 0xd58815  [node]\n' +
    ' 6: 0xd58ea6 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]\n' +
    ' 7: 0xd65765 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]\n' +
    ' 8: 0xd66615 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]\n' +
    ' 9: 0xd690cc v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]\n' +
    '10: 0xd35731 v8::internal::Factory::NewTransitionArray(int, int) [node]\n' +
    '11: 0xf7ec77 v8::internal::TransitionsAccessor::Insert(v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Map>, v8::internal::SimpleTransitionFlag) [node]\n' +
    '12: 0xf2adda v8::internal::Map::ConnectTransition(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::SimpleTransitionFlag) [node]\n' +
    '13: 0xf2d13a v8::internal::Map::ShareDescriptor(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::DescriptorArray>, v8::internal::Descriptor*) [node]\n' +
    '14: 0xf2db2e v8::internal::Map::CopyAddDescriptor(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Map>, v8::internal::Descriptor*, v8::internal::TransitionFlag) [node]\n' +
    '15: 0xf2dca9 v8::internal::Map::CopyWithField(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::FieldType>, v8::internal::PropertyAttributes, v8::internal::PropertyConstness, v8::internal::Representation, v8::internal::TransitionFlag) [node]\n' +
    '16: 0xf2f492 v8::internal::Map::TransitionToDataProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::PropertyConstness, v8::internal::StoreOrigin) [node]\n' +
    '17: 0xf1fb2f v8::internal::LookupIterator::PrepareTransitionToDataProperty(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::StoreOrigin) [node]\n' +
    '18: 0xdeb55b v8::internal::StoreIC::LookupForWrite(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::StoreOrigin) [node]\n' +
    '19: 0xdeefe7 v8::internal::StoreIC::UpdateCaches(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::StoreOrigin) [node]\n' +
    '20: 0xdf195c  [node]\n' +
    '21: 0xdf1fba v8::internal::Runtime_StoreIC_Miss(int, unsigned long*, v8::internal::Isolate*) [node]\n' +
    '22: 0x140e819  [node]\n' +
    'error Command failed with signal "SIGABRT".\n',
  failed: true,
  signal: null,
  cmd: 'yarn run build',
  timedOut: false,
  exitCode: 1
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Does this need more than 4GB RAM to build? Or do I need to customize some settings to get it to build?

Thanks

**Comment by ryanwoconnor** [comment]
Hi @gjanders take a look at the releases section on the homepage for this app. There is a download link there for the app itself: https://github.com/splunk/spling_bee_moderator/releases/tag/0.1.0. 

We have the source code here on Github in case anyone wants to modify the game for their own purposes or see how we built it.

**Comment by gjanders** [comment]
Thanks, I completely forgot to check the releases section

**Comment by ryanwoconnor** [comment]
Not a problem at all. It was good feedback that I should clarify the readme section. I've updated it to hopefully clear this up for others.

Thank you!
